version: '3.2'

services:
  shinken:
    build: 
      context: shinken/
    environment:
    - "TZ=UTC"  # UTC can be replaced by any valid timezone.
    ports:
      - "80:80"
      - "160-161:160-161"
    volumes:
      - ./custom_configs:/etc/shinken/custom_configs
      - ./extra_plugins:/usr/local/custom_plugins
      - type: bind
        source: ./shinken/config/packs
        target: /etc/shinken/packs
        read_only: true
    networks:
      main:
        ipv4_address: "172.25.0.10"
    restart: always
  client1:
    build:
      context: client/
    volumes:
      - type: bind
        source: ./client/config/snmpd.conf
        target: /etc/snmp/snmpd.conf
        read_only: true
    stdin_open: true
    tty: true
    networks:
      - main
    ports: 
      - "160-161"
  client2:
    build:
      context: client/
    volumes:
      - type: bind
        source: ./client/config/snmpd.conf
        target: /etc/snmp/snmpd.conf
        read_only: true
    stdin_open: true
    tty: true
    networks:
      - main
    ports: 
      - "160-161"
  client3:
    build:
      context: client/
    volumes:
      - type: bind
        source: ./client/config/snmpd.conf
        target: /etc/snmp/snmpd.conf
        read_only: true
    stdin_open: true
    tty: true
    networks:
      - main
    ports: 
      - "160-161"

networks:
  main:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.25.0.0/24"
      
