version: '3.2'

services:
  shinken:
    build: 
      context: shinken/
    ports:
      - "80:80"
    volumes:
      - ./custom_configs:/etc/shinken/custom_configs
      - ./extra_plugins:/usr/local/custom_plugins
    networks:
      main:
        ipv4_address: "172.26.0.10"
    stdin_open: true
    tty: true
    restart: always
  client1:
    build:
      context: client/
    volumes:
      - type: bind
        source: ./client/config/snmpd.conf
        target: /etc/snmp/snmpd.conf
        read_only: true
    stdin_open: true
    tty: true
    networks:
      main:
        ipv4_address: "172.26.0.11"
    links:
      - shinken
  client2:
    build:
      context: client/
    volumes:
      - type: bind
        source: ./client/config/snmpd.conf
        target: /etc/snmp/snmpd.conf
        read_only: true
    stdin_open: true
    tty: true
    networks:
      main:
        ipv4_address: "172.26.0.12"
    links:
      - shinken
  client3:
    build:
      context: client/
    volumes:
      - type: bind
        source: ./client/config/snmpd.conf
        target: /etc/snmp/snmpd.conf
        read_only: true
    stdin_open: true
    tty: true
    networks:
      main:
        ipv4_address: "172.26.0.13"
    ports: 
      - "160:160"
      - "161:161/udp"
      - "162:162"
    links:
      - shinken

networks:
  main:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.26.0.0/24"
      
